[package]
name = "ph"
version = "0.1.0"
authors = ["Piotr Beling <piotr.beling@wmii.uni.lodz.pl>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "The library of data structures based on perfect hashing."
documentation = "https://docs.rs/ph"
repository = "https://github.com/beling/bsuccinct-rs"
readme = "README.md"
include = [ "**/*.rs", "Cargo.toml", "README.md" ]
categories = [ "data-structures", "algorithms", "compression", "science" ]
keywords = [ "perfect", "hashing", "minimal", "map", "dictionary" ]

[dependencies]
bitm = { version=">=0.1", path="../bitm" }
dyn_size_of = { version=">=0.1", path="../dyn_size_of" }
binout = { version=">=0.1", path="../binout" }
rayon = "1.5"
wyhash = { version="0.5", optional=true }
fnv = { version="1", optional=true }

[dev-dependencies]
cpu-time = "1"
cmph-sys = { git = "https://github.com/beling/cmph-sys" }
boomphf = { git = "https://github.com/beling/rust-boomphf" }

[[example]]
name = "mphf_benchmark"
required-features = ["wyhash"]

